name: maktub
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  flutter_slidable: ^3.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 700
